[package]
name = "rust_os"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rust_os"
test = false
bench = false

[dependencies]
bootloader = "0.9"
spin = "0.5.2"
volatile = "0.2.6"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]